name: Coding Style Checks

on:
    workflow_dispatch

jobs:
    code-check:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout source code
          uses: actions/checkout@v2

        - name: Install Clang Format
          run: sudo apt-get install -y clang-format

        - name: Install Cppcheck
          run: sudo apt-get install -y cppcheck

        - name: Run Clang Format
          run: clang-format --version && find . -name '*.c' -exec clang-format -i -style=llvm {} \;

        - name: Run Cppcheck
          run: find . -name '*.c' -exec cppcheck --enable=all --error-exitcode=1 {} \;