# This is a workflow to get source code and check the coding style using clang-format and cppcheck
name: Coding Style Checks

on:
    # # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
    # Allows you to run this workflow every time a commit is pushed to the repository
    push:
      paths:
        - '.github/workflows/codeStyleCheck.yml'
    # Allows you to run this workflow every time a pull request is opened or updated
    pull_request:
      paths:
        - '.github/workflows/codeStyleCheck.yml'
    # Schedule a workflow to run automatically
    schedule:
      - cron:  '0 2 * * *'

jobs:
    code-style-check:
      runs-on: ubuntu-latest
      steps:
        # step to checkout the source code
        - name: Checkout source code
          uses: actions/checkout@main

        # step to install cppcheck
        - name: Install Cppcheck
          run: sudo apt-get install -y cppcheck

        # Step: Tool Versions
        - name: Tool Versions
          run: |
            cppcheck --version

        # step to run clang-format and cppcheck to check the code style
        - name: Run Clang Format & Cppcheck
          run: |
            chmod +x 00_Basics/03_Run_Tests/runCodingStyleCheck.sh
            ./00_Basics/03_Run_Tests/runCodingStyleCheck.sh

# TODO
# SecMissile
# Secbrella
# clangtidy
# cmetrics
# codecheck
# codemars
# codingStyle