# This is a workflow to get source code and check the coding style using clang-format and cppcheck
name: Coding Style Checks

on:
    # # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
    # Allows you to run this workflow every time a commit is pushed to the repository
    push:
      paths:
        - '00_Basics/01_Common_Func/**'
        - '.github/workflows/codeStyleCheck.yml'
    # Allows you to run this workflow every time a pull request is opened or updated
    pull_request:
      paths:
        - '00_Basics/01_Common_Func/**'
        - '.github/workflows/codeStyleCheck.yml'
    # Schedule a workflow to run automatically
    schedule:
      - cron:  '0 2 * * *'

jobs:
    # Job
    Cpplint-Style-Check:
      runs-on: ubuntu-latest
      steps:
        # step to checkout the source code
        - name: Checkout source code
          uses: actions/checkout@main

        # step to install cpplint
        - name: Install Cpplint
          run: pip install cpplint

        # Step: Tool Versions
        - name: Tool Versions
          run: |
            cpplint --version

        # step to run cpplint
        - name: Check Code Style
          run: |
            chmod +x .github/workflows/testRunner/runCpplint.sh
            .github/workflows/testRunner/runCpplint.sh

    Cppcheck-Style-Check:
      runs-on: ubuntu-latest
      steps:
        # step to checkout the source code
        - name: Checkout source code
          uses: actions/checkout@main

        # step to install cppcheck
        - name: Install Cppcheck
          run: sudo apt-get install -y cppcheck

        # Step: Tool Versions
        - name: Tool Versions
          run: |
            cppcheck --version

        # step to run clang-format and cppcheck to check the code style
        - name: Run Cppcheck
          run: |
            chmod +x .github/workflows/testRunner/runCppcheck.sh
            .github/workflows/testRunner/runCppcheck.sh

# TODO
# SecMissile
# Secbrella
# clangtidy
# cmetrics
# codecheck
# codemars
# codingStyle
# Clang Static Analyzer
# SonarQube
