# This is a workflow to get source code, check code style and run tests of common functions
name: Common Function Tests

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
    workflow_dispatch:
    push:
      paths:
        - '00_Basics/01_Common_Func/inc/**'
        - '00_Basics/01_Common_Func/src/**'
    pull_request:
      paths:
        - '00_Basics/01_Common_Func/inc/**'
        - '00_Basics/01_Common_Func/src/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # Job
    Test-Common-Functions:
      # Runner
      runs-on: ubuntu-latest
      steps:
        # Step: Checkout source code
        - name: Checkout source code
          uses: actions/checkout@main

        # Step: Setup CMake
        - name: Setup CMake
          uses: jwlawson/actions-setup-cmake@v1.9

        # Step: Cmake version
        - name: Cmake version
          run: cmake --version

        # Step: Build the project
        - name: Build the project
          run: |
            mkdir build
            cd build
            cmake ..
            cmake --build .

        # Step: Run all executables in the build/bin directory
        - name: Run executables
          run: |
            find ./build/bin -executable -type f -exec {} \;
            echo "All executables have been run!"
