# This is a workflow to get source code, check code style and run tests of common functions
name: C Common Function Tests

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
    workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # Job
    Test-Common-Functions:
      # Runner
      runs-on: ubuntu-latest
      steps:
        # Step: Checkout source code
        - name: Checkout source code
          uses: actions/checkout@v2

        # Step
        - name: Test Common Functions
          run: echo "Test all common Functions"
