# This is a workflow to get source code, check code style and run tests of common functions
name: Common Function Tests

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
    workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # Job: Check Code Style
    Check-Code-Style:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      steps:
        # Step: Get Source Code
        - name: Get Source Code
          run: echo "Get Source Code"

        # Step: Check Code Style
        - name: Check Code Style
          run: echo "Check Code Style"

    # Job: Test Common Functions
    Test-Common-Functions:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      steps:
        # Step: Get Source Code
        - name: Get Source Code
          run: echo "Get Source Code"

        # Step: Test Common Funcs
        - name: Test Common Funcs
          run: echo "Test all common Functions"

