# This is a workflow to get source code, check code style and run tests of common functions
name: Common Function Tests

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
    workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # Job
    Check-Code-Style:
      # Runner
      runs-on: ubuntu-latest
      steps:
        # Step
        - name: Get Source Code
          run: echo "Get Source Code"

        # Step
        - name: Check Code Style
          run: echo "Check Code Style"

    # Job
    Test-Common-Functions:
      # Runner
      runs-on: ubuntu-latest
      steps:
        # Step
        - name: Get Source Code
          run: echo "Get Source Code"

        # Step
        - name: Test Common Functions
          run: echo "Test all common Functions"
