# This is a workflow to get source code, check code style and run tests of common functions
name: Common Function Tests

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
    workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # Job: Get Source Code
    GetSourceCode:
      runs-on: ubuntu-latest
      steps:
        - name: Get Source Code
          run: echo "Get Source Code"

    # Job: Check Code Style
    CheckCodeStyle:
      runs-on: ubuntu-latest
      steps:
        - name: Check Code Style
          run: echo "Check Code Style"

    # Job: Run Tests
    RunTests:
      runs-on: ubuntu-latest
      steps:
        - name: Test Common Funcs
          run: echo "Test all common Functions"